name: WorldEditSlimefun
version: '${project.version}'
main: dev.j3fftw.worldeditslimefun.WorldEditSlimefun
api-version: '26.2'
authors: [J3fftw1]
contributors: [wickidcow]
website: https://github.com/wickidcow/WorldEditSlimefun
depend:
  - Slimefun
  - WorldEdit

permissions:
  wesf.*:
    description: Provides permissions for all WorldEditSlimefun functions
    default: op
    children:
      wesf.admin: true
  wesf.admin:
    description: Allows WorldEditSlimefun editing, audit and recovery commands
    default: op
